const BASE = 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500';

export const TEAM_LOGOS: Record<string, string> = {
  akron: `${BASE}/2006.png`,
  alabama: `${BASE}/333.png`,
  arizona: `${BASE}/12.png`,
  arkansas: `${BASE}/8.png`,
  byu: `${BASE}/252.png`,
  'cal-baptist': `${BASE}/25.png`,
  clemson: `${BASE}/228.png`,
  duke: `${BASE}/150.png`,
  florida: `${BASE}/57.png`,
  furman: `${BASE}/231.png`,
  georgia: `${BASE}/61.png`,
  gonzaga: `${BASE}/2250.png`,
  hawaii: `${BASE}/62.png`,
  'high-point': `${BASE}/2272.png`,
  hofstra: `${BASE}/2275.png`,
  houston: `${BASE}/248.png`,
  howard: `${BASE}/47.png`,
  idaho: `${BASE}/70.png`,
  illinois: `${BASE}/356.png`,
  iowa: `${BASE}/2294.png`,
  'iowa-state': `${BASE}/66.png`,
  kansas: `${BASE}/2305.png`,
  'kennesaw-state': `${BASE}/338.png`,
  kentucky: `${BASE}/96.png`,
  liu: `${BASE}/112358.png`,
  louisville: `${BASE}/97.png`,
  mcneese: `${BASE}/2377.png`,
  'miami-fl': `${BASE}/2390.png`,
  'miami-oh': `${BASE}/193.png`,
  michigan: `${BASE}/130.png`,
  'michigan-state': `${BASE}/127.png`,
  missouri: `${BASE}/142.png`,
  nebraska: `${BASE}/158.png`,
  'north-carolina': `${BASE}/153.png`,
  'north-dakota-state': `${BASE}/2449.png`,
  'northern-iowa': `${BASE}/2460.png`,
  'ohio-state': `${BASE}/194.png`,
  penn: `${BASE}/219.png`,
  'prairie-view': `${BASE}/2504.png`,
  purdue: `${BASE}/2509.png`,
  queens: `${BASE}/2511.png`,
  'saint-louis': `${BASE}/139.png`,
  'saint-marys': `${BASE}/2608.png`,
  'santa-clara': `${BASE}/2541.png`,
  siena: `${BASE}/2561.png`,
  'south-florida': `${BASE}/58.png`,
  'st-johns': `${BASE}/2599.png`,
  tcu: `${BASE}/2628.png`,
  tennessee: `${BASE}/2633.png`,
  'tennessee-state': `${BASE}/2634.png`,
  texas: `${BASE}/251.png`,
  'texas-am': `${BASE}/245.png`,
  'texas-tech': `${BASE}/2641.png`,
  troy: `${BASE}/2653.png`,
  ucf: `${BASE}/2116.png`,
  ucla: `${BASE}/26.png`,
  uconn: `${BASE}/41.png`,
  'utah-state': `${BASE}/328.png`,
  vanderbilt: `${BASE}/238.png`,
  vcu: `${BASE}/2670.png`,
  villanova: `${BASE}/222.png`,
  virginia: `${BASE}/258.png`,
  wisconsin: `${BASE}/275.png`,
  'wright-state': `${BASE}/2750.png`,
};

export function getTeamLogoUri(teamId: string) {
  return TEAM_LOGOS[teamId] ?? null;
}
